# Generated by Django 3.1.7 on 2022-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Quetta', 'Quetta'), ('Islamabad', 'Islamabad'), ('Multan', 'Multan'), ('Hyderabad', 'Hyderabad'), ('Jamshoro', 'Jamshoro'), ('Shikarpur', 'Shikarpur'), ('Sukkur', 'Sukkur'), ('Larkana', 'Larkana'), ('Peshawar', 'Peshawar'), ('Sargodha', 'Sargodha'), ('Faisalabad', 'Faisalabad'), ('Rawalpindi', 'Rawalpindi'), ('Gujranwala', 'Gujranwala'), ('Sialkot', 'Sialkot'), ('Bahawalpur', 'Bahawalpur'), ('Kandhkot', 'Kandhkot'), ('Gujrat', 'Gujrat'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Sahiwal', 'Sahiwal'), ('Nawabshah', 'Nawabshah'), ('Jhelum', 'Jhelum'), ('Jacobabad', 'Jacobabad'), ('Khuzdar', 'Khuzdar')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.ImageField(blank=True, upload_to='doc')),
            ],
        ),
    ]
